# Dependencies
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: 'Nathan Kleyn'
tagline: 'The musings of a programming fanatic'
description: 'Ruby, Haskell, Rust, and JS tinkerer. Find me on Twitter as <a href="https://twitter.com/nathankleyn" target="_blank">@nathankleyn</a>.'
url: http://nathankleyn.com
baseurl: /
include: ['.well-known']

author:
  name: 'Nathan Kleyn'
  url: https://twitter.com/nathankleyn

paginate: 5

sass:
  sass_dir: css/_sass
  style: compressed
