# Dependencies
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: 'Nathan Kleyn'
tagline: 'The musings of a programming fanatic'
description: 'Scala by day — Rust, Ruby and Haskell by night. I hail from London.'
url: https://nathankleyn.com
baseurl: /
include: ['.well-known']

author:
  name: 'Nathan Kleyn'
  url: https://nathankleyn.com

plugins:
  - jekyll-paginate
paginate: 5

sass:
  sass_dir: css/_sass
  style: compressed
